### ISSUE TITLE
Broken pipe error

### ISSUE THREAD

**Issue by tfe** [epicsf/epic-video-archive#1]
Is the part number just a coincidence?

```
Capture0000.mov part 10001.......Traceback (most recent call last):
  File "/Users/video/Dropbox/Scripts/epic-video-archive/app.py", line 36, in <module>
    main()
  File "/Users/video/Dropbox/Scripts/epic-video-archive/app.py", line 29, in main
    s3_manager.upload(connection, bucket, drive)    
  File "/Users/video/Dropbox/Scripts/epic-video-archive/s3_manager.py", line 51, in upload
    mp.upload_part_from_file(fp, fp_num, cb=_percent_complete, num_cb=10, size=settings.s3_max_file_part_size)
  File "/Library/Python/2.7/site-packages/boto/s3/multipart.py", line 260, in upload_part_from_file
    query_args=query_args, size=size)
  File "/Library/Python/2.7/site-packages/boto/s3/key.py", line 1291, in set_contents_from_file
    chunked_transfer=chunked_transfer, size=size)
  File "/Library/Python/2.7/site-packages/boto/s3/key.py", line 748, in send_file
    chunked_transfer=chunked_transfer, size=size)
  File "/Library/Python/2.7/site-packages/boto/s3/key.py", line 949, in _send_file_internal
    query_args=query_args
  File "/Library/Python/2.7/site-packages/boto/s3/connection.py", line 664, in make_request
    retry_handler=retry_handler
  File "/Library/Python/2.7/site-packages/boto/connection.py", line 1068, in make_request
    retry_handler=retry_handler)
  File "/Library/Python/2.7/site-packages/boto/connection.py", line 939, in _mexe
    request.body, request.headers)
  File "/Library/Python/2.7/site-packages/boto/s3/key.py", line 842, in sender
    http_conn.send(chunk)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 805, in send
    self.sock.sendall(data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 229, in sendall
    v = self.send(data[count:])
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 198, in send
    v = self._sslobj.write(data)
socket.error: [Errno 32] Broken pipe
```

**Comment by tfe** [comment]
@tknickman So there is actually a 10K part limit which is the only reason this was failing. I tweaked the config setting for part size to make sure we didn't exceed 10K parts on files up to 250GB.

**Comment by tknickman** [comment]
@tfe Nice, have you tested yet?

**Comment by tfe** [comment]
It’s running now and not done yet but I don’t see any reason it would fail.
One question I have is what happens if a part upload fails… will it retry?
for how long? Not sure how often this would be a problem so maybe it
doesn’t matter.

**Comment by tknickman** [comment]
Cool, lmk. And that's a good question. I would assume the `upload_part_from_file` function that I used (https://github.com/epicsf/epic-video-archive/blob/master/s3_manager.py#L51) would handle some sort of retry - but I'll check the docs.

**Comment by tknickman** [comment]
Couldn't find anything in the docs, here's a nice little recursive upload function using the same function that handles any exceptions - I'll read into this a little more soon. 
https://gist.github.com/fabiant7t/924094#file-s3_multipart_upload-py-L16-L36

**Comment by tknickman** [comment]
@tfe I just did a simple test:
1. kicked off a large video upload. 
2. In the middle of a part upload, I killed my WiFi.
   The upload just hung for around 25 seconds. 
3. Reenabled WiFi.
   Upload continued where it had left off. 

So there is some type of a retry on each part upload. There must be a retry num or timeout we can set somewhere. But this should hopefully be good for now.
